"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WinstonChurchill = exports.Shaka = exports.RamessesII = exports.OttoVonBismarck = exports.NapoleonI = exports.MoctezumaII = exports.MaoZedong = exports.MahatmaGandhi = exports.JuliusCaesar = exports.JosephStalin = exports.Hammurabi = exports.GeorgeWashington = exports.GenghisKhan = exports.FrederickTheGreat = exports.ElizabethI = exports.CatherineTheGreat = exports.AlexanderTheGreat = exports.AbrahamLincoln = void 0;
var AbrahamLincoln_1 = require("./Leaders/AbrahamLincoln");
Object.defineProperty(exports, "AbrahamLincoln", { enumerable: true, get: function () { return AbrahamLincoln_1.AbrahamLincoln; } });
var AlexanderTheGreat_1 = require("./Leaders/AlexanderTheGreat");
Object.defineProperty(exports, "AlexanderTheGreat", { enumerable: true, get: function () { return AlexanderTheGreat_1.AlexanderTheGreat; } });
var CatherineTheGreat_1 = require("./Leaders/CatherineTheGreat");
Object.defineProperty(exports, "CatherineTheGreat", { enumerable: true, get: function () { return CatherineTheGreat_1.CatherineTheGreat; } });
var ElizabethI_1 = require("./Leaders/ElizabethI");
Object.defineProperty(exports, "ElizabethI", { enumerable: true, get: function () { return ElizabethI_1.ElizabethI; } });
var FrederickTheGreat_1 = require("./Leaders/FrederickTheGreat");
Object.defineProperty(exports, "FrederickTheGreat", { enumerable: true, get: function () { return FrederickTheGreat_1.FrederickTheGreat; } });
var GenghisKhan_1 = require("./Leaders/GenghisKhan");
Object.defineProperty(exports, "GenghisKhan", { enumerable: true, get: function () { return GenghisKhan_1.GenghisKhan; } });
var GeorgeWashington_1 = require("./Leaders/GeorgeWashington");
Object.defineProperty(exports, "GeorgeWashington", { enumerable: true, get: function () { return GeorgeWashington_1.GeorgeWashington; } });
var Hammurabi_1 = require("./Leaders/Hammurabi");
Object.defineProperty(exports, "Hammurabi", { enumerable: true, get: function () { return Hammurabi_1.Hammurabi; } });
var JosephStalin_1 = require("./Leaders/JosephStalin");
Object.defineProperty(exports, "JosephStalin", { enumerable: true, get: function () { return JosephStalin_1.JosephStalin; } });
var JuliusCaesar_1 = require("./Leaders/JuliusCaesar");
Object.defineProperty(exports, "JuliusCaesar", { enumerable: true, get: function () { return JuliusCaesar_1.JuliusCaesar; } });
var MahatmaGandhi_1 = require("./Leaders/MahatmaGandhi");
Object.defineProperty(exports, "MahatmaGandhi", { enumerable: true, get: function () { return MahatmaGandhi_1.MahatmaGandhi; } });
var MaoZedong_1 = require("./Leaders/MaoZedong");
Object.defineProperty(exports, "MaoZedong", { enumerable: true, get: function () { return MaoZedong_1.MaoZedong; } });
var MoctezumaII_1 = require("./Leaders/MoctezumaII");
Object.defineProperty(exports, "MoctezumaII", { enumerable: true, get: function () { return MoctezumaII_1.MoctezumaII; } });
var NapoleonI_1 = require("./Leaders/NapoleonI");
Object.defineProperty(exports, "NapoleonI", { enumerable: true, get: function () { return NapoleonI_1.NapoleonI; } });
var OttoVonBismarck_1 = require("./Leaders/OttoVonBismarck");
Object.defineProperty(exports, "OttoVonBismarck", { enumerable: true, get: function () { return OttoVonBismarck_1.OttoVonBismarck; } });
var RamessesII_1 = require("./Leaders/RamessesII");
Object.defineProperty(exports, "RamessesII", { enumerable: true, get: function () { return RamessesII_1.RamessesII; } });
var Shaka_1 = require("./Leaders/Shaka");
Object.defineProperty(exports, "Shaka", { enumerable: true, get: function () { return Shaka_1.Shaka; } });
var WinstonChurchill_1 = require("./Leaders/WinstonChurchill");
Object.defineProperty(exports, "WinstonChurchill", { enumerable: true, get: function () { return WinstonChurchill_1.WinstonChurchill; } });
//# sourceMappingURL=Leaders.js.map